### ISSUE TITLE
[panic] The use file panic

### ISSUE THREAD

**Issue by enomothem** [pwnwriter/haylxon#30]
```
thread 'thread 'thread 'thread 'thread 'thread 'tokio-runtime-workertokio-runtime-workertokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value' panicked at '', src\cli\screenshot.rs:' panicked at '158called `Option::unwrap()` on a `None` value:', 64src\cli\screenshot.rs
:note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
158tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Option::unwrap()` on a `None` value', :src\cli\screenshot.rscalled `Option::unwrap()` on a `None` value:', 158tokio-runtime-worker64:' panicked at 'src\cli\screenshot.rscalled `Option::unwrap()` on a `None` value64

:158:called `Option::unwrap()` on a `None` value64', ', src\cli\screenshot.rssrc\cli\screenshot.rs::158:64

158:64
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\screenshot.rs:158:64
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\screenshot.rs:158:64
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\screenshot.rs:158:64
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\screenshot.rs:158:64
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\screenshot.rs:158:64
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\screenshot.rs:158:64
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\screenshot.rs:158:64
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\screenshot.rs:158:64
error: task 36 panicked
```

**Comment by pwnwriter** [comment]
Can you give me overall what command were you running? Seems like it panicked while fetching `url` title.

**Comment by pwnwriter** [comment]
WoOoO :P

**Comment by enomothem** [comment]
@pwnwriter 
The command I used.
`.\hxn.exe -f 1.txt -b "C:\Program Files\Google\Chrome\Application\chrome.exe"`
I don't know why it panicked, but I tried to set the thread to 1 and timeout 20, and it didn't go well, so I think it might have something to do with the url, if there was a problem with the page I visited, was there no exception handling

**Comment by pwnwriter** [comment]
Hey, it used to panic if the url or the website doesn't have a title. Now it will just set 'no title' to those urls. 

You can tryout latest build :0
